project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Pinhao (Eric) Xiang"

  page-footer:
    left: "&copy; Copyright 2024, Pinhao (Eric) Xiang"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home

      - href: projects/index.qmd
        text: Projects

      - href: Volunteer.qmd
        text: Volunteer
     
      - href: quarto.qmd
        text: quarto
        
      - href: casualphoto/index.qmd
        text: casual photo
       
     

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



