---
title: "Mentorship Activities"
editor: visual
subtitle: "Here is a list of mentorship."
---

-   **Science Undergraduate Society Undergraduate Mentor 2023 Sept-Dec**

    I had monthly meetings with my mentee and provided him with career and research advice. The mentee is currently working at UBC as a lab assistant.

-   **Undergraduate Research Co-Mentor, University of British Columbia 2023 Jan-Aug**

    I co-supervised two undergraduate students to provide experimental design and data analysis support. I organized social gatherings to help the students integrate into the lab environments and offered tips to help them achieve their professional goals. Currently, one student is working as the research assistant in our lab and another student is pursuing medical education at UBC.

-   **Undergraduate Career Mentor, University of British Columbia 2023 Jan-April**

    I participated in the Mentorship Program offered by the Science Undergraduate Society at UBC. I offered my graduate student experience to one biology undergraduate student who was interested in pursuing life science research. I helped her revise her resume and cover letter for research co-op job applications. Currently, she is working as a research assistant at UBC.
