---
title: "Volunteer and Extracurrcular activities"
subtitle: "Here is an overview of the activities I was or have benn part of "
editor: 
  markdown: 
    wrap: sentence
---

**1.HLI High School Student Outreach, 2024 November**

• Showed 11 high school students, without prior knowledge, how to perform tissue culture.

• Shared graduate school experiences with the students.

**2.UBC Undergraduate Research Student Mentor, 2024 September-Present**

• Taught an undergraduate student to conduct a literature review on fasting and nonfasting lipid fractions in cardiovascular risk prediction.

• Supported the student to draft an abstract and presentation for the UBC Multidisciplinary Undergraduate Research Conference (MURC).

**3. Science to Business Vancouver to Victoria Chapter, 2024 January-Present**

• Organized the Introduction to Start Up in BC event with 50 attendees and 90% survey satisfaction rate.
• Responsible for obtaining \$300 Graduate Student Society funding to support the event.

**4. HLI Professional development and Scholarship chair, 2023 September-current**

• Collaborated with HirePhD to invite four speakers to HLI to share local job market opportunities.
The event had 40 trainees attend who engaged with the speakers.

• Organized Lunch and Learn sessions to facilitate trainee interactions with Friday Seminar speakers.
The events happened 3 times with \~15 trainees attending each session.

**5. HLI Research Day, Conference Organizing team member 2022 May-2024 August**

• Co-chaired the 2024 HLI Research Day for which I helped schedule the program.
• Organized the Knowledge Translation Video Competition (10 trainees participated).

• 40 students had the opportunity to present their research projects to 125 attendees.

**6. Co-Chair of the HLI Mentorship Program, HLI 2021 September- 2023 September:**

• Recruited and led a group of committees to match junior students with senior graduate students.

• Organized and hosted two annual CareerSeminarsr to support the trainees’ career goals.
Each event had \~30 participants with a 90% rating from the survey.

• Raised \$650 to support mentorship networking and career exploration events.

• Recruited and trained a new chair to continue the mentorship program.

\
**7. UBC Graduate Student Ambassador, 2022 September-Present**

• Connected with prospective newly admitted UBC students through the UBC welcoming webinar with 100 participants in each session.
• Hosted the “Living in Vancouver” webinar to help students adapt to student living in the city.
• Responded to graduate student questions in the Student Community Forum.
